#include <stdio.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#define RANGE_START 0
#define RANGE_END 255
int main(void) {
    int width, height;
    unsigned char *data = stbi_load("ConsoleFont.bmp", &width, &height, NULL, 1);
    if (data == NULL) {
        fprintf(stderr, "ERROR: failed to load image: %s", stbi_failure_reason());
        return 1;
    }


    int glyph_width = width / (RANGE_END - RANGE_START);
    int glyph_height = height;

    printf("/* Generated by %s */\n", __FILE__);
    printf("#define GLYPH_WIDTH %d\n", glyph_width);
    printf("#define GLYPH_HEIGHT %d\n", glyph_height);
    printf("typedef struct {\n");
    printf("    // NOTE: 0 or 1\n");
    printf("    int img[GLYPH_HEIGHT][GLYPH_WIDTH];\n");
    printf("} Glyph;\n");
    printf("#ifdef DECLARE_FONT\n");
    printf("Glyph font[] = {\n");
    int x0 = 0;
    for (unsigned char ch = RANGE_START; ch < RANGE_END; ch++) {
        printf("    [%hu] = {{\n", ch);
        for (int y = 0; y < glyph_height; y++) {
            printf("        {");
            for (int dx = 0; dx < glyph_width; dx++) {
                int x = x0 + dx;
                unsigned char pixel = data[y * width + x];
                if (pixel < 127) {
                    printf("0,");
                } else {
                    printf("1,");
                }
            }
            printf("},\n");
        }
        printf("    }},\n");
        x0 += glyph_width;
    }
    printf("};\n");
    printf("#else // !defined(DECLARE_FONT)\n");
    printf("extern Glyph font[];\n");
    printf("#endif // DECLARE_FONT\n");
}
